### ISSUE TITLE
壁纸页面不正常

### ISSUE THREAD

**Issue by wangtz1** [couldflyer/Joe-Revised#1]
在后台添加壁纸的独立页面以后，无法正常显示，显示内容如下
![问题](https://github.com/user-attachments/assets/e8e11332-acd0-4483-bbfe-8ba4a7896c64)
我也安装了Joe7.7.1官方版做测试，官方的壁纸页面可以正常显示
![原版](https://github.com/user-attachments/assets/1fea1b5d-d70c-48a6-84eb-7cf61112c644)

然后我也尝试用官方版的wallpaper文件替换过来测试，尝试解决该问题，结果预览壁纸页面直接出现报错，无法打开

同时我也测试了视频页和直播页，都是正常可以显示的，效果和官方相同，只有壁纸页面有这个奇怪的问题

**Comment by couldflyer** [comment]
不是哥，我只是存一下文件，原作者删库了，我也不知道怎么解决
